//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.PostamatNovyjj
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Адрес.
    /// </summary>
    // *** Start programmer edit section *** (Адрес CustomAttributes)

    // *** End programmer edit section *** (Адрес CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("АдресE", new string[] {
            "Адрес as \'Адрес\'",
            "СлужбаДоставки as \'Служба доставки\'",
            "СлужбаДоставки.Наименование as \'Наименование\'"}, Hidden=new string[] {
            "СлужбаДоставки.Наименование"})]
    [MasterViewDefineAttribute("АдресE", "СлужбаДоставки", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Наименование")]
    [View("АдресL", new string[] {
            "Адрес as \'Адрес\'",
            "СлужбаДоставки.Наименование as \'Наименование\'"})]
    public class Адрес : ICSSoft.STORMNET.DataObject
    {
        
        private string fАдрес;
        
        private IIS.PostamatNovyjj.СлужбаДоставки fСлужбаДоставки;
        
        // *** Start programmer edit section *** (Адрес CustomMembers)

        // *** End programmer edit section *** (Адрес CustomMembers)

        
        /// <summary>
        /// Адрес.
        /// </summary>
        // *** Start programmer edit section *** (Адрес.Адрес CustomAttributes)

        // *** End programmer edit section *** (Адрес.Адрес CustomAttributes)
        [StrLen(255)]
        public virtual string Адрес
        {
            get
            {
                // *** Start programmer edit section *** (Адрес.Адрес Get start)

                // *** End programmer edit section *** (Адрес.Адрес Get start)
                string result = this.fАдрес;
                // *** Start programmer edit section *** (Адрес.Адрес Get end)

                // *** End programmer edit section *** (Адрес.Адрес Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Адрес.Адрес Set start)

                // *** End programmer edit section *** (Адрес.Адрес Set start)
                this.fАдрес = value;
                // *** Start programmer edit section *** (Адрес.Адрес Set end)

                // *** End programmer edit section *** (Адрес.Адрес Set end)
            }
        }
        
        /// <summary>
        /// Адрес.
        /// </summary>
        // *** Start programmer edit section *** (Адрес.СлужбаДоставки CustomAttributes)

        // *** End programmer edit section *** (Адрес.СлужбаДоставки CustomAttributes)
        [PropertyStorage(new string[] {
                "СлужбаДоставки"})]
        [NotNull()]
        public virtual IIS.PostamatNovyjj.СлужбаДоставки СлужбаДоставки
        {
            get
            {
                // *** Start programmer edit section *** (Адрес.СлужбаДоставки Get start)

                // *** End programmer edit section *** (Адрес.СлужбаДоставки Get start)
                IIS.PostamatNovyjj.СлужбаДоставки result = this.fСлужбаДоставки;
                // *** Start programmer edit section *** (Адрес.СлужбаДоставки Get end)

                // *** End programmer edit section *** (Адрес.СлужбаДоставки Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Адрес.СлужбаДоставки Set start)

                // *** End programmer edit section *** (Адрес.СлужбаДоставки Set start)
                this.fСлужбаДоставки = value;
                // *** Start programmer edit section *** (Адрес.СлужбаДоставки Set end)

                // *** End programmer edit section *** (Адрес.СлужбаДоставки Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "АдресE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View АдресE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("АдресE", typeof(IIS.PostamatNovyjj.Адрес));
                }
            }
            
            /// <summary>
            /// "АдресL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View АдресL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("АдресL", typeof(IIS.PostamatNovyjj.Адрес));
                }
            }
        }
    }
}
