//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.PostamatNovyjj
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Код.
    /// </summary>
    // *** Start programmer edit section *** (Код CustomAttributes)

    // *** End programmer edit section *** (Код CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("КодE", new string[] {
            "СгенКод as \'Сген код\'",
            "Получатель as \'Получатель\'",
            "Получатель.ФИО as \'ФИО\'"}, Hidden=new string[] {
            "Получатель.ФИО"})]
    [MasterViewDefineAttribute("КодE", "Получатель", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "ФИО")]
    [View("КодL", new string[] {
            "СгенКод as \'Сген код\'",
            "Получатель.ФИО as \'ФИО\'"})]
    public class Код : ICSSoft.STORMNET.DataObject
    {
        
        private int fСгенКод;
        
        private IIS.PostamatNovyjj.Получатель fПолучатель;
        
        // *** Start programmer edit section *** (Код CustomMembers)

        // *** End programmer edit section *** (Код CustomMembers)

        
        /// <summary>
        /// СгенКод.
        /// </summary>
        // *** Start programmer edit section *** (Код.СгенКод CustomAttributes)

        // *** End programmer edit section *** (Код.СгенКод CustomAttributes)
        public virtual int СгенКод
        {
            get
            {
                // *** Start programmer edit section *** (Код.СгенКод Get start)

                // *** End programmer edit section *** (Код.СгенКод Get start)
                int result = this.fСгенКод;
                // *** Start programmer edit section *** (Код.СгенКод Get end)

                // *** End programmer edit section *** (Код.СгенКод Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Код.СгенКод Set start)

                // *** End programmer edit section *** (Код.СгенКод Set start)
                this.fСгенКод = value;
                // *** Start programmer edit section *** (Код.СгенКод Set end)

                // *** End programmer edit section *** (Код.СгенКод Set end)
            }
        }
        
        /// <summary>
        /// Код.
        /// </summary>
        // *** Start programmer edit section *** (Код.Получатель CustomAttributes)

        // *** End programmer edit section *** (Код.Получатель CustomAttributes)
        [PropertyStorage(new string[] {
                "Получатель"})]
        [NotNull()]
        public virtual IIS.PostamatNovyjj.Получатель Получатель
        {
            get
            {
                // *** Start programmer edit section *** (Код.Получатель Get start)

                // *** End programmer edit section *** (Код.Получатель Get start)
                IIS.PostamatNovyjj.Получатель result = this.fПолучатель;
                // *** Start programmer edit section *** (Код.Получатель Get end)

                // *** End programmer edit section *** (Код.Получатель Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Код.Получатель Set start)

                // *** End programmer edit section *** (Код.Получатель Set start)
                this.fПолучатель = value;
                // *** Start programmer edit section *** (Код.Получатель Set end)

                // *** End programmer edit section *** (Код.Получатель Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "КодE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View КодE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("КодE", typeof(IIS.PostamatNovyjj.Код));
                }
            }
            
            /// <summary>
            /// "КодL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View КодL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("КодL", typeof(IIS.PostamatNovyjj.Код));
                }
            }
        }
    }
}
