//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.PostamatNovyjj
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Постамат.
    /// </summary>
    // *** Start programmer edit section *** (Постамат CustomAttributes)

    // *** End programmer edit section *** (Постамат CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ПостаматE", new string[] {
            "НомерПост as \'Номер постамата\'",
            "СтатПост as \'Статус постамата\'",
            "Адрес as \'Адрес\'",
            "Адрес.Адрес as \'Адрес\'",
            "Адрес.СлужбаДоставки.Наименование as \'Наименование службы доставки\'"}, Hidden=new string[] {
            "Адрес.Адрес"})]
    [AssociatedDetailViewAttribute("ПостаматE", "Ячейка", "ЯчейкаE", true, "", "Ячейка", true, new string[] {
            ""})]
    [MasterViewDefineAttribute("ПостаматE", "Адрес", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Адрес")]
    [View("ПостаматL", new string[] {
            "НомерПост as \'Номер постамата\'",
            "СтатПост as \'Стат постамата\'",
            "Адрес.Адрес as \'Адрес\'",
            "Адрес.СлужбаДоставки.Наименование as \'Наименование службы доставки\'"})]
    public class Постамат : ICSSoft.STORMNET.DataObject
    {
        
        private int fНомерПост;
        
        private IIS.PostamatNovyjj.СтатПост fСтатПост;
        
        private IIS.PostamatNovyjj.Адрес fАдрес;
        
        private IIS.PostamatNovyjj.DetailArrayOfЯчейка fЯчейка;
        
        // *** Start programmer edit section *** (Постамат CustomMembers)

        // *** End programmer edit section *** (Постамат CustomMembers)

        
        /// <summary>
        /// НомерПост.
        /// </summary>
        // *** Start programmer edit section *** (Постамат.НомерПост CustomAttributes)

        // *** End programmer edit section *** (Постамат.НомерПост CustomAttributes)
        public virtual int НомерПост
        {
            get
            {
                // *** Start programmer edit section *** (Постамат.НомерПост Get start)

                // *** End programmer edit section *** (Постамат.НомерПост Get start)
                int result = this.fНомерПост;
                // *** Start programmer edit section *** (Постамат.НомерПост Get end)

                // *** End programmer edit section *** (Постамат.НомерПост Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Постамат.НомерПост Set start)

                // *** End programmer edit section *** (Постамат.НомерПост Set start)
                this.fНомерПост = value;
                // *** Start programmer edit section *** (Постамат.НомерПост Set end)

                // *** End programmer edit section *** (Постамат.НомерПост Set end)
            }
        }
        
        /// <summary>
        /// СтатПост.
        /// </summary>
        // *** Start programmer edit section *** (Постамат.СтатПост CustomAttributes)

        // *** End programmer edit section *** (Постамат.СтатПост CustomAttributes)
        public virtual IIS.PostamatNovyjj.СтатПост СтатПост
        {
            get
            {
                // *** Start programmer edit section *** (Постамат.СтатПост Get start)

                // *** End programmer edit section *** (Постамат.СтатПост Get start)
                IIS.PostamatNovyjj.СтатПост result = this.fСтатПост;
                // *** Start programmer edit section *** (Постамат.СтатПост Get end)

                // *** End programmer edit section *** (Постамат.СтатПост Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Постамат.СтатПост Set start)

                // *** End programmer edit section *** (Постамат.СтатПост Set start)
                this.fСтатПост = value;
                // *** Start programmer edit section *** (Постамат.СтатПост Set end)

                // *** End programmer edit section *** (Постамат.СтатПост Set end)
            }
        }
        
        /// <summary>
        /// Постамат.
        /// </summary>
        // *** Start programmer edit section *** (Постамат.Адрес CustomAttributes)

        // *** End programmer edit section *** (Постамат.Адрес CustomAttributes)
        [PropertyStorage(new string[] {
                "Адрес"})]
        [NotNull()]
        public virtual IIS.PostamatNovyjj.Адрес Адрес
        {
            get
            {
                // *** Start programmer edit section *** (Постамат.Адрес Get start)

                // *** End programmer edit section *** (Постамат.Адрес Get start)
                IIS.PostamatNovyjj.Адрес result = this.fАдрес;
                // *** Start programmer edit section *** (Постамат.Адрес Get end)

                // *** End programmer edit section *** (Постамат.Адрес Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Постамат.Адрес Set start)

                // *** End programmer edit section *** (Постамат.Адрес Set start)
                this.fАдрес = value;
                // *** Start programmer edit section *** (Постамат.Адрес Set end)

                // *** End programmer edit section *** (Постамат.Адрес Set end)
            }
        }
        
        /// <summary>
        /// Постамат.
        /// </summary>
        // *** Start programmer edit section *** (Постамат.Ячейка CustomAttributes)

        // *** End programmer edit section *** (Постамат.Ячейка CustomAttributes)
        public virtual IIS.PostamatNovyjj.DetailArrayOfЯчейка Ячейка
        {
            get
            {
                // *** Start programmer edit section *** (Постамат.Ячейка Get start)

                // *** End programmer edit section *** (Постамат.Ячейка Get start)
                if ((this.fЯчейка == null))
                {
                    this.fЯчейка = new IIS.PostamatNovyjj.DetailArrayOfЯчейка(this);
                }
                IIS.PostamatNovyjj.DetailArrayOfЯчейка result = this.fЯчейка;
                // *** Start programmer edit section *** (Постамат.Ячейка Get end)

                // *** End programmer edit section *** (Постамат.Ячейка Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Постамат.Ячейка Set start)

                // *** End programmer edit section *** (Постамат.Ячейка Set start)
                this.fЯчейка = value;
                // *** Start programmer edit section *** (Постамат.Ячейка Set end)

                // *** End programmer edit section *** (Постамат.Ячейка Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ПостаматE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПостаматE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПостаматE", typeof(IIS.PostamatNovyjj.Постамат));
                }
            }
            
            /// <summary>
            /// "ПостаматL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПостаматL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПостаматL", typeof(IIS.PostamatNovyjj.Постамат));
                }
            }
        }
    }
}
