//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.PostamatNovyjj
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Служба доставки.
    /// </summary>
    // *** Start programmer edit section *** (СлужбаДоставки CustomAttributes)

    // *** End programmer edit section *** (СлужбаДоставки CustomAttributes)
    [AutoAltered()]
    [Caption("Служба доставки")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("СлужбаДоставкиE", new string[] {
            "Номер as \'Номер\'",
            "Наименование as \'Наименование\'",
            "Адрес as \'Адрес\'",
            "Телефон as \'Телефон\'"})]
    [View("СлужбаДоставкиL", new string[] {
            "Номер as \'Номер\'",
            "Наименование as \'Наименование\'",
            "Адрес as \'Адрес\'",
            "Телефон as \'Телефон\'"})]
    public class СлужбаДоставки : ICSSoft.STORMNET.DataObject
    {
        
        private int fНомер;
        
        private string fНаименование;
        
        private string fАдрес;
        
        private int fТелефон;
        
        // *** Start programmer edit section *** (СлужбаДоставки CustomMembers)

        // *** End programmer edit section *** (СлужбаДоставки CustomMembers)

        
        /// <summary>
        /// Адрес.
        /// </summary>
        // *** Start programmer edit section *** (СлужбаДоставки.Адрес CustomAttributes)

        // *** End programmer edit section *** (СлужбаДоставки.Адрес CustomAttributes)
        [StrLen(255)]
        public virtual string Адрес
        {
            get
            {
                // *** Start programmer edit section *** (СлужбаДоставки.Адрес Get start)

                // *** End programmer edit section *** (СлужбаДоставки.Адрес Get start)
                string result = this.fАдрес;
                // *** Start programmer edit section *** (СлужбаДоставки.Адрес Get end)

                // *** End programmer edit section *** (СлужбаДоставки.Адрес Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СлужбаДоставки.Адрес Set start)

                // *** End programmer edit section *** (СлужбаДоставки.Адрес Set start)
                this.fАдрес = value;
                // *** Start programmer edit section *** (СлужбаДоставки.Адрес Set end)

                // *** End programmer edit section *** (СлужбаДоставки.Адрес Set end)
            }
        }
        
        /// <summary>
        /// Наименование.
        /// </summary>
        // *** Start programmer edit section *** (СлужбаДоставки.Наименование CustomAttributes)

        // *** End programmer edit section *** (СлужбаДоставки.Наименование CustomAttributes)
        [StrLen(255)]
        public virtual string Наименование
        {
            get
            {
                // *** Start programmer edit section *** (СлужбаДоставки.Наименование Get start)

                // *** End programmer edit section *** (СлужбаДоставки.Наименование Get start)
                string result = this.fНаименование;
                // *** Start programmer edit section *** (СлужбаДоставки.Наименование Get end)

                // *** End programmer edit section *** (СлужбаДоставки.Наименование Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СлужбаДоставки.Наименование Set start)

                // *** End programmer edit section *** (СлужбаДоставки.Наименование Set start)
                this.fНаименование = value;
                // *** Start programmer edit section *** (СлужбаДоставки.Наименование Set end)

                // *** End programmer edit section *** (СлужбаДоставки.Наименование Set end)
            }
        }
        
        /// <summary>
        /// Номер.
        /// </summary>
        // *** Start programmer edit section *** (СлужбаДоставки.Номер CustomAttributes)

        // *** End programmer edit section *** (СлужбаДоставки.Номер CustomAttributes)
        public virtual int Номер
        {
            get
            {
                // *** Start programmer edit section *** (СлужбаДоставки.Номер Get start)

                // *** End programmer edit section *** (СлужбаДоставки.Номер Get start)
                int result = this.fНомер;
                // *** Start programmer edit section *** (СлужбаДоставки.Номер Get end)

                // *** End programmer edit section *** (СлужбаДоставки.Номер Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СлужбаДоставки.Номер Set start)

                // *** End programmer edit section *** (СлужбаДоставки.Номер Set start)
                this.fНомер = value;
                // *** Start programmer edit section *** (СлужбаДоставки.Номер Set end)

                // *** End programmer edit section *** (СлужбаДоставки.Номер Set end)
            }
        }
        
        /// <summary>
        /// Телефон.
        /// </summary>
        // *** Start programmer edit section *** (СлужбаДоставки.Телефон CustomAttributes)

        // *** End programmer edit section *** (СлужбаДоставки.Телефон CustomAttributes)
        public virtual int Телефон
        {
            get
            {
                // *** Start programmer edit section *** (СлужбаДоставки.Телефон Get start)

                // *** End programmer edit section *** (СлужбаДоставки.Телефон Get start)
                int result = this.fТелефон;
                // *** Start programmer edit section *** (СлужбаДоставки.Телефон Get end)

                // *** End programmer edit section *** (СлужбаДоставки.Телефон Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СлужбаДоставки.Телефон Set start)

                // *** End programmer edit section *** (СлужбаДоставки.Телефон Set start)
                this.fТелефон = value;
                // *** Start programmer edit section *** (СлужбаДоставки.Телефон Set end)

                // *** End programmer edit section *** (СлужбаДоставки.Телефон Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "СлужбаДоставкиE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СлужбаДоставкиE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СлужбаДоставкиE", typeof(IIS.PostamatNovyjj.СлужбаДоставки));
                }
            }
            
            /// <summary>
            /// "СлужбаДоставкиL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СлужбаДоставкиL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СлужбаДоставкиL", typeof(IIS.PostamatNovyjj.СлужбаДоставки));
                }
            }
        }
    }
}
