//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.PostamatNovyjj
{
    using System;
    using System.Xml;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Стат пост.
    /// </summary>
    // *** Start programmer edit section *** (СтатПост CustomAttributes)

    // *** End programmer edit section *** (СтатПост CustomAttributes)
    public enum СтатПост
    {
        
        // *** Start programmer edit section *** (СтатПост.1 CustomAttributes)

        // *** End programmer edit section *** (СтатПост.1 CustomAttributes)
        1,
        
        // *** Start programmer edit section *** (СтатПост.2 CustomAttributes)

        // *** End programmer edit section *** (СтатПост.2 CustomAttributes)
        2,
    }
}
